services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    image: frontend
    volumes:
      - ./certs:/etc/letsencrypt
	  - ./webroot:/var/www/html
	  - nginx-config:/etc/nginx
    ports:
      - "80:80"
      - "443:443"
  certbot:
    image: certbot/certbot
    entrypoint: >
      certbot --nginx
      --staging
      --email mockingbird48763@email.com
      --agree-tos
      --no-eff-email
      -d mockingbird48763.online
      -d www.mockingbird48763.online
    volumes:
      - ./certs:/etc/letsencrypt
	  - ./webroot:/var/www/html
	  - nginx-config:/etc/nginx
volumes:
  nginx-config: